import type { Product, BlogPost, Testimonial } from "@shared/schema";

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Gilgit Almonds",
    slug: "premium-gilgit-almonds",
    description: "Our premium almonds are sourced directly from the pristine orchards of Gilgit-Baltistan, where the unique climate and altitude create the perfect conditions for growing exceptionally flavorful nuts. These almonds are naturally dried using traditional methods passed down through generations, ensuring maximum retention of nutrients and authentic taste.\n\nRich in vitamin E, healthy fats, and protein, these almonds make an excellent addition to your daily diet. Whether enjoyed as a snack, added to your morning oatmeal, or used in cooking and baking, their superior quality shines through in every bite.",
    shortDescription: "Hand-picked from Gilgit orchards, naturally dried for maximum flavor and nutrition.",
    price: 1299,
    originalPrice: 1499,
    category: "dry-fruits",
    images: ["/products/almonds-1.jpg", "/products/almonds-2.jpg"],
    benefits: ["Rich in Vitamin E", "Heart-healthy fats", "High protein content", "Natural energy booster", "Supports brain health"],
    ingredients: "100% Natural Almonds from Gilgit-Baltistan",
    sourcingStory: "Harvested from family-owned orchards in Hunza Valley, where almonds have been cultivated for over 500 years.",
    weight: "500g",
    inStock: true,
    featured: true,
    bestSeller: true,
    rating: 4.9,
    reviewCount: 234,
  },
  {
    id: "2",
    name: "Organic Hunza Walnuts",
    slug: "organic-hunza-walnuts",
    description: "Hunza Valley walnuts are renowned worldwide for their exceptional quality and rich, buttery flavor. Grown in the high-altitude regions where the air is pure and the soil is mineral-rich, these walnuts develop a distinctive taste that sets them apart from ordinary varieties.\n\nPacked with omega-3 fatty acids, antioxidants, and essential minerals, Hunza walnuts are nature's perfect brain food. The traditional harvesting and processing methods ensure that every nut retains its natural goodness.",
    shortDescription: "World-famous Hunza walnuts with rich, buttery flavor and superior nutrition.",
    price: 1499,
    originalPrice: 1799,
    category: "dry-fruits",
    images: ["/products/walnuts-1.jpg", "/products/walnuts-2.jpg"],
    benefits: ["Omega-3 rich", "Brain health support", "Antioxidant properties", "Heart-healthy", "Natural sleep aid"],
    ingredients: "100% Organic Walnuts from Hunza Valley",
    sourcingStory: "Collected from ancient walnut groves in Hunza, some trees over 300 years old.",
    weight: "500g",
    inStock: true,
    featured: true,
    bestSeller: true,
    rating: 4.8,
    reviewCount: 189,
  },
  {
    id: "3",
    name: "Dried Hunza Apricots",
    slug: "dried-hunza-apricots",
    description: "Hunza apricots are legendary for their exceptional sweetness and health benefits. Dried naturally under the mountain sun, these apricots retain their vibrant color and concentrated nutrients. The unique climate of Hunza Valley gives these apricots a flavor profile that cannot be replicated anywhere else in the world.\n\nThese sun-dried treasures are rich in iron, potassium, and dietary fiber. Locals attribute their famous longevity to the regular consumption of these remarkable fruits.",
    shortDescription: "Sun-dried Hunza apricots, naturally sweet and packed with iron and fiber.",
    price: 899,
    originalPrice: 1099,
    category: "dry-fruits",
    images: ["/products/apricots-1.jpg", "/products/apricots-2.jpg"],
    benefits: ["High in iron", "Rich in potassium", "Excellent fiber source", "Natural sweetness", "Energy boosting"],
    ingredients: "100% Sun-Dried Apricots from Hunza Valley",
    sourcingStory: "Dried using centuries-old solar drying techniques on rooftops overlooking the Karakoram mountains.",
    weight: "400g",
    inStock: true,
    featured: true,
    bestSeller: false,
    rating: 4.7,
    reviewCount: 156,
  },
  {
    id: "4",
    name: "Pure Himalayan Shilajit",
    slug: "pure-himalayan-shilajit",
    description: "Our premium Shilajit is harvested from the high-altitude rocks of the Karakoram and Himalayan ranges, where it forms naturally over centuries. This mineral-rich resin is considered one of nature's most powerful supplements, prized in Ayurvedic medicine for thousands of years.\n\nEach batch is carefully tested for purity and potency, ensuring you receive authentic, high-quality Shilajit. Rich in fulvic acid, humic acid, and over 85 minerals, this remarkable substance supports energy, vitality, and overall wellness.",
    shortDescription: "Authentic high-altitude Shilajit, lab-tested for purity and potency.",
    price: 3499,
    originalPrice: 3999,
    category: "shilajit",
    images: ["/products/shilajit-1.jpg", "/products/shilajit-2.jpg"],
    benefits: ["Natural energy booster", "Supports cognitive function", "Rich in minerals", "Enhances vitality", "Immune system support"],
    ingredients: "100% Pure Himalayan Shilajit Resin",
    sourcingStory: "Collected by experienced harvesters from rocks above 16,000 feet in the Karakoram range.",
    weight: "30g",
    inStock: true,
    featured: true,
    bestSeller: true,
    rating: 4.9,
    reviewCount: 312,
  },
  {
    id: "5",
    name: "Wild Mountain Honey",
    slug: "wild-mountain-honey",
    description: "This exceptional honey is harvested from wild bee colonies in the remote forests of Gilgit-Baltistan. The bees forage on a diverse range of wildflowers, medicinal herbs, and alpine plants, creating a complex flavor profile and exceptional nutritional value.\n\nCompletely raw and unprocessed, this honey retains all its natural enzymes, antioxidants, and beneficial compounds. Its dark amber color and rich, complex taste make it a premium choice for health-conscious consumers.",
    shortDescription: "Raw, unfiltered honey from wild mountain bees, rich in natural enzymes.",
    price: 1899,
    originalPrice: 2199,
    category: "honey",
    images: ["/products/honey-1.jpg", "/products/honey-2.jpg"],
    benefits: ["100% raw and unfiltered", "Natural antibacterial properties", "Rich in antioxidants", "Immune boosting", "Natural energy source"],
    ingredients: "100% Raw Wild Mountain Honey",
    sourcingStory: "Harvested sustainably from wild bee colonies in the pristine forests of Skardu.",
    weight: "500g",
    inStock: true,
    featured: true,
    bestSeller: true,
    rating: 4.8,
    reviewCount: 201,
  },
  {
    id: "6",
    name: "Cold-Pressed Almond Oil",
    slug: "cold-pressed-almond-oil",
    description: "Our premium almond oil is extracted using traditional cold-pressing methods from the finest Gilgit almonds. This gentle process preserves all the natural nutrients, vitamins, and beneficial compounds that make almond oil so valuable for both culinary and cosmetic use.\n\nRich in vitamin E, omega fatty acids, and natural antioxidants, this versatile oil is perfect for cooking, skincare, and hair care. Its light, nutty flavor enhances dishes while its moisturizing properties nourish skin and hair.",
    shortDescription: "Traditional cold-pressed almond oil, perfect for cooking and skincare.",
    price: 1599,
    originalPrice: 1899,
    category: "oils",
    images: ["/products/almond-oil-1.jpg", "/products/almond-oil-2.jpg"],
    benefits: ["Rich in Vitamin E", "Natural moisturizer", "Heart-healthy cooking oil", "Hair nourishment", "Antioxidant properties"],
    ingredients: "100% Cold-Pressed Almond Oil",
    sourcingStory: "Pressed from premium Gilgit almonds using traditional stone grinding methods.",
    weight: "250ml",
    inStock: true,
    featured: false,
    bestSeller: false,
    rating: 4.7,
    reviewCount: 98,
  },
  {
    id: "7",
    name: "Apricot Kernel Oil",
    slug: "apricot-kernel-oil",
    description: "Extracted from the kernels of Hunza apricots, this golden oil is a beauty secret that has been used in the region for centuries. Cold-pressed to preserve its natural properties, apricot kernel oil is lightweight yet deeply nourishing.\n\nIts high content of vitamins A and E, along with essential fatty acids, makes it ideal for skincare. It absorbs quickly without leaving a greasy residue, making it perfect for facial care, massage, and as a carrier oil for aromatherapy.",
    shortDescription: "Light, nourishing oil from Hunza apricot kernels for skin and hair care.",
    price: 1399,
    originalPrice: 1599,
    category: "oils",
    images: ["/products/apricot-oil-1.jpg", "/products/apricot-oil-2.jpg"],
    benefits: ["Lightweight and fast-absorbing", "Rich in vitamins A & E", "Anti-aging properties", "Natural skin softener", "Excellent for massage"],
    ingredients: "100% Cold-Pressed Apricot Kernel Oil",
    sourcingStory: "Made from the kernels of sun-dried Hunza apricots, using traditional extraction methods.",
    weight: "200ml",
    inStock: true,
    featured: false,
    bestSeller: false,
    rating: 4.6,
    reviewCount: 76,
  },
  {
    id: "8",
    name: "Premium Cashew Nuts",
    slug: "premium-cashew-nuts",
    description: "Our carefully selected cashews are roasted to perfection, bringing out their natural sweetness and satisfying crunch. These premium nuts are chosen for their size, flavor, and quality, ensuring you receive only the best.\n\nCashews are an excellent source of healthy fats, protein, and essential minerals like magnesium and zinc. Whether enjoyed as a snack or used in cooking, their creamy texture and mild flavor make them incredibly versatile.",
    shortDescription: "Premium roasted cashews, carefully selected for quality and flavor.",
    price: 1699,
    originalPrice: 1999,
    category: "dry-fruits",
    images: ["/products/cashews-1.jpg", "/products/cashews-2.jpg"],
    benefits: ["Rich in healthy fats", "Good protein source", "Contains essential minerals", "Supports bone health", "Heart-healthy snack"],
    ingredients: "100% Premium Cashew Nuts",
    sourcingStory: "Selected from the finest crops and roasted using traditional methods for optimal flavor.",
    weight: "400g",
    inStock: true,
    featured: false,
    bestSeller: false,
    rating: 4.7,
    reviewCount: 112,
  },
  {
    id: "9",
    name: "Organic Medjool Dates",
    slug: "organic-medjool-dates",
    description: "Known as the 'king of dates', Medjool dates are prized for their large size, soft texture, and rich caramel-like flavor. These organic dates are carefully harvested at peak ripeness to ensure maximum sweetness and nutritional value.\n\nPacked with natural sugars, fiber, and essential nutrients, dates are a perfect natural energy source. They're ideal for snacking, baking, or as a natural sweetener in smoothies and desserts.",
    shortDescription: "Large, soft Medjool dates with rich caramel flavor, naturally sweet.",
    price: 1199,
    originalPrice: 1399,
    category: "dry-fruits",
    images: ["/products/dates-1.jpg", "/products/dates-2.jpg"],
    benefits: ["Natural energy boost", "High in fiber", "Rich in potassium", "Natural sweetener", "Supports digestive health"],
    ingredients: "100% Organic Medjool Dates",
    sourcingStory: "Sourced from organic date farms and carefully packed to preserve freshness.",
    weight: "500g",
    inStock: true,
    featured: false,
    bestSeller: false,
    rating: 4.8,
    reviewCount: 145,
  },
  {
    id: "10",
    name: "Cold-Pressed Walnut Oil",
    slug: "cold-pressed-walnut-oil",
    description: "Made from the finest Hunza walnuts, this cold-pressed oil captures the rich, nutty essence of these legendary nuts. Its deep golden color and intense flavor make it a gourmet addition to any kitchen.\n\nWalnut oil is exceptionally rich in omega-3 fatty acids and antioxidants. It's perfect for salad dressings, finishing dishes, and adding a sophisticated nutty flavor to your cooking. Its skincare benefits include moisturizing and anti-aging properties.",
    shortDescription: "Gourmet cold-pressed walnut oil from premium Hunza walnuts.",
    price: 1799,
    originalPrice: 2099,
    category: "oils",
    images: ["/products/walnut-oil-1.jpg", "/products/walnut-oil-2.jpg"],
    benefits: ["Highest omega-3 content", "Rich nutty flavor", "Antioxidant properties", "Heart-healthy", "Gourmet quality"],
    ingredients: "100% Cold-Pressed Walnut Oil",
    sourcingStory: "Pressed from premium Hunza walnuts, capturing their legendary rich flavor.",
    weight: "250ml",
    inStock: true,
    featured: false,
    bestSeller: false,
    rating: 4.7,
    reviewCount: 67,
  },
  {
    id: "11",
    name: "Acacia Honey",
    slug: "acacia-honey",
    description: "This light, delicate honey comes from bees that forage primarily on acacia blossoms in the lower valleys of Gilgit-Baltistan. Its mild, sweet flavor and slow crystallization make it a favorite among honey connoisseurs.\n\nAcacia honey is known for its high fructose content, which gives it a mild sweetness that doesn't overpower. It's perfect for sweetening tea, drizzling over yogurt, or enjoying with cheese and fruits.",
    shortDescription: "Light, delicate acacia honey with mild sweetness and floral notes.",
    price: 1599,
    originalPrice: 1799,
    category: "honey",
    images: ["/products/acacia-honey-1.jpg", "/products/acacia-honey-2.jpg"],
    benefits: ["Slow crystallization", "Mild, delicate flavor", "Natural antibacterial", "Rich in antioxidants", "Perfect for tea"],
    ingredients: "100% Pure Acacia Honey",
    sourcingStory: "Collected from beekeepers in the acacia-rich valleys near Gilgit.",
    weight: "500g",
    inStock: true,
    featured: false,
    bestSeller: false,
    rating: 4.6,
    reviewCount: 89,
  },
  {
    id: "12",
    name: "Shilajit Capsules",
    slug: "shilajit-capsules",
    description: "For those who prefer convenience without compromising on quality, our Shilajit capsules offer the same premium Himalayan Shilajit in an easy-to-take form. Each capsule contains a precise dose of purified Shilajit extract.\n\nThese capsules are perfect for busy lifestyles, travel, or anyone who prefers not to taste the strong flavor of raw Shilajit. Each bottle contains a 60-day supply at the recommended dosage.",
    shortDescription: "Convenient capsule form of pure Himalayan Shilajit, 60-day supply.",
    price: 2499,
    originalPrice: 2899,
    category: "shilajit",
    images: ["/products/shilajit-caps-1.jpg", "/products/shilajit-caps-2.jpg"],
    benefits: ["Convenient dosing", "No strong taste", "Travel-friendly", "Same premium quality", "60-day supply"],
    ingredients: "Purified Himalayan Shilajit Extract, Vegetable Capsule",
    sourcingStory: "Made from the same premium Shilajit, processed and encapsulated for convenience.",
    weight: "60 capsules",
    inStock: true,
    featured: false,
    bestSeller: false,
    rating: 4.8,
    reviewCount: 178,
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "The Amazing Health Benefits of Almonds You Need to Know",
    slug: "health-benefits-of-almonds",
    excerpt: "Discover why almonds are considered a superfood and how incorporating them into your daily diet can transform your health.",
    content: "Almonds are one of nature's most perfect foods...",
    category: "Nutrition",
    image: "/blog/almonds-benefits.jpg",
    author: "Dr. Sarah Khan",
    publishedAt: "2024-12-15",
    readTime: 5,
  },
  {
    id: "2",
    title: "How Shilajit Improves Energy and Vitality Naturally",
    slug: "shilajit-energy-vitality",
    excerpt: "Learn about the ancient Ayurvedic wisdom behind Shilajit and its remarkable effects on energy, focus, and overall wellness.",
    content: "Shilajit has been used for thousands of years...",
    category: "Wellness",
    image: "/blog/shilajit-benefits.jpg",
    author: "Ayush Sharma",
    publishedAt: "2024-12-10",
    readTime: 7,
  },
  {
    id: "3",
    title: "The Secret to Hunza Valley's Famous Longevity",
    slug: "hunza-valley-longevity-secret",
    excerpt: "Explore what makes the people of Hunza Valley live such long, healthy lives and how you can adopt their dietary habits.",
    content: "The Hunza people are renowned for their exceptional longevity...",
    category: "Lifestyle",
    image: "/blog/hunza-valley.jpg",
    author: "Ali Hassan",
    publishedAt: "2024-12-05",
    readTime: 6,
  },
  {
    id: "4",
    title: "Why Raw Honey is Nature's Perfect Medicine",
    slug: "raw-honey-natural-medicine",
    excerpt: "Uncover the medicinal properties of raw, unprocessed honey and why it's been used as a healing agent for millennia.",
    content: "Raw honey has been valued for its medicinal properties...",
    category: "Health",
    image: "/blog/raw-honey.jpg",
    author: "Dr. Sarah Khan",
    publishedAt: "2024-11-28",
    readTime: 5,
  },
  {
    id: "5",
    title: "Cold-Pressed vs. Regular Oils: What's the Difference?",
    slug: "cold-pressed-vs-regular-oils",
    excerpt: "Understanding why cold-pressed oils are superior and how the extraction method affects nutritional value.",
    content: "When it comes to cooking and skincare oils...",
    category: "Education",
    image: "/blog/cold-pressed-oils.jpg",
    author: "Chef Fatima",
    publishedAt: "2024-11-20",
    readTime: 4,
  },
  {
    id: "6",
    title: "Traditional Recipes Using Dry Fruits from Gilgit-Baltistan",
    slug: "traditional-dry-fruit-recipes",
    excerpt: "Authentic recipes from the mountain communities that showcase the versatility of premium dry fruits.",
    content: "The cuisine of Gilgit-Baltistan features dry fruits prominently...",
    category: "Recipes",
    image: "/blog/dry-fruit-recipes.jpg",
    author: "Chef Fatima",
    publishedAt: "2024-11-15",
    readTime: 8,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Ahmed Malik",
    location: "Lahore, Pakistan",
    content: "The quality of almonds and walnuts from HealthyHills is exceptional. You can taste the difference immediately. I've been ordering for 6 months and the consistency is remarkable.",
    rating: 5,
  },
  {
    id: "2",
    name: "Priya Sharma",
    location: "Delhi, India",
    content: "I was skeptical about Shilajit at first, but after using HealthyHills' product for 2 months, my energy levels have improved significantly. The quality is authentic and the service is excellent.",
    rating: 5,
  },
  {
    id: "3",
    name: "John Smith",
    location: "London, UK",
    content: "Finally found a reliable source for genuine Himalayan products. The wild mountain honey is unlike anything I've tasted before - pure and incredibly flavorful.",
    rating: 5,
  },
  {
    id: "4",
    name: "Fatima Abbas",
    location: "Karachi, Pakistan",
    content: "The apricot oil has transformed my skincare routine. It's light, absorbs quickly, and has made my skin so much softer. Love the natural products!",
    rating: 5,
  },
  {
    id: "5",
    name: "Michael Chen",
    location: "Singapore",
    content: "Fast international shipping and excellent packaging. The dry fruits arrived fresh and were of premium quality. Highly recommend for anyone seeking authentic products.",
    rating: 4,
  },
  {
    id: "6",
    name: "Sarah Johnson",
    location: "New York, USA",
    content: "As a nutritionist, I'm very particular about quality. HealthyHills products meet my high standards. The Hunza apricots are now a staple in my diet recommendations.",
    rating: 5,
  },
];
